Saved so far with new version of import/discover script

diff --git a/src/main/resources/scripts/import b/src/main/resources/scripts/import
--- a/src/main/resources/scripts/import
+++ b/src/main/resources/scripts/import
@@ -20,33 +20,46 @@ log_file="$log_dir/import.log"
 # Ensure log directory exists
 mkdir -p "$log_dir"
 
-> "$log_file"  # This clears the file or creates it if it doesn't exist
+# Clear the log file or create it if it doesn't exist
+> "$log_file"
 
 # Timestamp in ISO-8601 format
-timestamp="$(date --iso-8601=seconds)"
+timestamp="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
 
 # Iterate over entities sequentially
 for entity in "${entities[@]}"; do
+
     entity_log="$log_dir/import_$entity.log"
-    
-    # Add extra parameter if entity is NIA_VIEW
-    extra_params=""
+    echo "Starting discovery for entity: $entity with job: import, vendor: $vendor, circle: $circle" | tee -a "$log_file"
+
+    CMD="$ECI_STITCHING_HOME/scripts/discover --job=import --vendor=$vendor --db_profile=PROD --circle=$circle --entity=$entity --timestamp=$timestamp"
+
+    # Add extra argument for NIA_VIEW
     if [ "$entity" == "NIA_VIEW" ]; then
-        extra_params="--view_name=ECI_SDH_ALL"
+        CMD+=" --view_name=ECI_SDH_ALL"
     fi
 
-    echo "Starting discovery for entity: $entity with job: import, vendor: $vendor, circle: $circle" >> "$log_file"
-    $ECI_STITCHING_HOME/scripts/discover --job="import" --vendor="$vendor" --circle="$circle" --db_profile=PROD --entity="$entity" --timestamp="$timestamp" $extra_params > "$entity_log" 2>&1
-    EXIT_CODE=$?
+    echo "CMD to execution: $CMD" | tee -a "$log_file"
 
-    # Log the exit code
-    echo "Discovery for entity: $entity completed with exit code: $EXIT_CODE" >> "$log_file"
+    # Run command and capture PID
+    $CMD > "$entity_log" 2>&1 &
+    PID=$!
 
-    if [ $EXIT_CODE -ne 0 ]; then
-        echo "Error occurred for entity: $entity. Exit code: $EXIT_CODE. Aborting remaining tasks." >> "$log_file"
-        exit $EXIT_CODE
-    fi
-    echo "Completed discovery for entity: $entity" | tee -a "$log_file"
+    echo "Launched discover process PID: $PID for entity: $entity" | tee -a "$log_file"
+
+    # Wait for the process to finish and capture its exit code
+    #wait $PID
+    #EXIT_CODE=$?
+
+    while ps -p $PID > /dev/null 2>&1; do
+        echo "Waiting for PID $PID for entity: $entity to exit..."
+        sleep 5
+    done
+
+    echo "Completed discovery for entity: $entity " | tee -a "$log_file"
+
+
+
 done
 
-echo "All entities processed successfully for job: import, vendor: $vendor, circle: $circle." >> "$log_file"
+echo "All entities processed successfully for job: import, vendor: $vendor, circle: $circle." | tee -a "$log_file"
